id: I8656639A
ocr_import_info:
  bdrc_scan_id: W1KG3397
  source: bdrc
  ocr_info:
    timestamp: '2022-08-25T00:00:00Z'
  batch_id: batch-0001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-01-21 16:44:11.671168
last_modified: 2022-08-25 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3397
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3397
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བ་མདོའི་དགོངས་པ་གསལ་བར་བྱེད་པ།
  languages:
  - bo
  author: དགེ་འདུན་གྲུབ་པ།
bases:
  I1KG3476:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3476
      total_pages: 940
      volume_number: 2
      volume_pages_bdrc_intro: 2
    base_file: I1KG3476.txt
    order: 1
  I1KG3475:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3475
      total_pages: 1040
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1KG3475.txt
    order: 2
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
